### ISSUE TITLE
Installed Python scripts last modified date is incorrect

### ISSUE THREAD

**Issue by emfrost** [park-bench/gpgmailer#27]
At some point debuild changes the last modified date on every file in the package to whatever the latest date in debian/changelog is. When Python imports any of our libraries, it will import the byte-compiled .pyc file with a later date and effectively run an old version of the library. This started occurring for me when I upgraded to Ubuntu 17.10.

The workaround we have been using is to set the environment variable PYTHONDONTWRITEBYTECODE with systemd, but that is not a long term solution. We are probably doing packaging wrong somehow.

**Comment by eviljoel** [comment]
We can get around this issue by building with:
$ SOURCE_DATE_EPOCH=`date +%s` debuild

Closing.
